# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and # 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of #the even-valued terms.

fibbonacciSequence = [1,2]
sum = 0

while fibbonacciSequence.last <= 4000000
    fibbonacciSequence.push (fibbonacciSequence[-1] + fibbonacciSequence[-2])
end

fibbonacciSequence.each do |n|
    if n % 2 == 0 && n <= 4000000
        sum += n
    end
end

puts sum